stages:
  - Build
  - Deploy

before_script:
  - export BASE_URL=${BASE_URL:-$(echo $CI_PROJECT_URL |  cut -d'/' -f1-3)}

Dashboard-Frontend:
  stage: Build
  script:
    - >
      if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
        echo "Deploying $CI_COMMIT_REF_NAME"
      elif [ "$CI_COMMIT_REF_NAME" == "production" ]; then
        echo "Deploying $CI_COMMIT_REF_NAME"
      else
        echo "No Matching Environment Could Be Found"
        exit 1
      fi
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull --no-cache -t "$CI_REGISTRY_IMAGE/frontend-$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE/frontend-$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA"

Deploy-Frontend:
  stage: Deploy
  image: crosscloudci/helm:latest
  script:
    - >
      if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
        echo "Deploying $CI_COMMIT_REF_NAME"
        export BACKEND_INGRESS="https://devapi.cncf.ci/api"
        export FRONTEND_INGRESS="dev.cncf.ci"
        export TLS="true"
      elif [ "$CI_COMMIT_REF_NAME" == "production" ]; then
        echo "Deploying $CI_COMMIT_REF_NAME"
        export BACKEND_INGRESS="https://productionapi.cncf.ci/api"
        export FRONTEND_INGRESS="cncf.ci"
        export TLS="true"
      else
        echo "No Matching Environment Could Be Found"
        exit 1
      fi
    - /helm/entrypoint.sh
    - export KUBECONFIG=/kubeconfig
    - helm repo add cncf http://cncf.gitlab.io/stable
    - helm upgrade fnt-"$CI_COMMIT_REF_NAME" cncf/frontend --install --wait --timeout 60m --set tls="$TLS" --set imagePullSecrets=productionsecret --set ingress.host="$FRONTEND_INGRESS" --set ingress.port=8080 --set api.url="$BACKEND_INGRESS" --set node.port=8080 --set node.host=0.0.0.0 --set image.repository="$CI_REGISTRY_IMAGE/frontend-$CI_COMMIT_REF_NAME" --set image.tag="$CI_COMMIT_SHA"
