export const RECEIVE_DASHBOARD_PROJECTS = 'RECEIVE_DASHBOARD_PROJECTS'
export const RECEIVE_PIPELINES = 'RECEIVE_PIPELINES'
export const RECEIVE_CLOUDS = 'RECEIVE_CLOUDS'
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED'
export const DASHBOARD_CONNECTED_TO_CHANNEL = 'DASHBOARD_CONNECTED_TO_CHANNEL'

