apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- if .Values.isClusterService }}
    k8s-app: {{ .Chart.Name | quote }}
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Frontend"
    {{- else }}
    app: {{ .Values.name }}
    {{- end }}
spec:
  selector:
  {{- if .Values.isClusterService }}
    k8s-app: {{ .Chart.Name | quote }}
  {{- else }}
    app: {{ .Values.name }}
  {{- end }}
  ports:
  - name: frontend
    port: 8080
  type: {{ .Values.serviceType }}
